services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=hotels-booking
        ports:
            - 1000:5432
        volumes:
            - hotels-db:/var/lib/postgresql/data

volumes:
    hotels-db:
